#!/bin/bash

set -eu

trap ctrl_c_sig INT

ctrl_c_sig() {
    echo "** Trapped (Running Clear Actions) CTRL-C"
    clear
}

i=1
declare -a options
declare -a raw_options
while read -r line; do
    program_name=$(echo "$line" | grep -oP ".+(?=\/)")
    options+=("$i" "$program_name" off)
    raw_options+=("$program_name")
    let "i=i+1"
done

choices=$(dialog --stdout --clear \
    --backtitle "Go Back" \
    --title "Purge Programs from apt" \
    --ok-label "PURGE" \
    --cancel-label "EXIT" \
    --output-fd 1 \
    --checklist "Choose Items to purge:" \
    60 120 ${#options[@]} "${options[@]}") || clear

clear

for choice in ${choices[@]}; do
    purge_program=${raw_options[(($choice - 1))]}
    echo "Purgeing: $purge_program"
    yes | sudo apt-get purge "$purge_program"
    echo "Cleaning"
    yes | sudo apt autoremove
    yes | sudo apt autoclean
done
