#!/usr/bin/env python3
import os
import sys

EXIT_SUCCESS = 0
EXIT_FAILURE = 1


# INFO: this is not save code
def main(args) -> int:
    file = args[1]
    remote = "lukasjoc@192.168.178.28"
    library_path = "/home/lukasjoc/library"
    sync_path = "/home/lukasjoc/.calibrecp"

    rsync_ok = os.system(f"rsync -Paz {file} {remote}:{sync_path}")

    ssh_ok = os.system(
        f"ssh {remote} calibredb \
            --library-path={library_path} add {sync_path}/{os.path.basename(file)}"
    )

    return ssh_ok or rsync_ok


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"usage: {sys.argv[0]} [file]")
        print("Error: need file to sync")
        sys.exit(EXIT_FAILURE)

    exit_code = main(args=sys.argv)
    sys.exit(exit_code)
