#!/bin/bash

playlist_url="https://www.youtube.com/watch?v=G0_sJSP2RhU&list=PLamVddj-8SIlOZ8Cmm9MoPUTv_C5k4JBV" ## replace with url
youtube-dl -j --flat-playlist "$playlist_url" | jq -r '.id' | sed 's_^_https://youtu.be/_' > urls.txt
for video in $(cat urls.txt); do
  youtube-dl -j --flat "$video" >> data.json
done
