#!/bin/bash

git fetch --all --prune --prune-tags --progress
git worktree prune

for br in $(git branch --format '%(refname:short) tracking:%(upstream:track)' | grep -E "\[gone\]" | awk '{print $1}'); do
    if [[ $(git worktree list --porcelain | grep -we "$br") ]]; then
        git worktree remove "$br"
    fi
    git branch -D "$br"
done
