#!/bin/bash

readonly gopath_local="$(go env GOPATH)"
readonly gobin_local="$(go env GOBIN)"

if ! echo "$PATH" | grep -q "$gopath_local"; then
  echo "could not find gopath in path"
  exit 1
fi

echo "GOPATH found at $gopath_local"

exit 0
