#!/bin/bash

# Convert dir of HTML files to markdown with pandoc
find . -name "*.html*" |
while IFS= read -r line
do
  src_file=$(basename -- "$line")
  md_file="${src_file%.*}.md"
  pandoc "$line" "$line" -o "$md_file"
  mkdir output
  mv "*.md" output/
done

