#!/bin/bash
set -u
# Installs Docker and Docker-Compose on Ubuntu 20.04 (amd64)
# !!Warning: Also Sets up a new group membership to the current user see line 19
# !!Warning: Also sets up a new alias as "dc" this may overwrite an existing program called dc

echo "Prepare starting..."
sudo apt update; sudo apt upgrade

echo "Installing Docker"

sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io

if command -v docker >& /dev/null; then echo "Docker installed.."; else echo "Error installing docker"; exit 1; fi
sudo systemctl status docker
sudo usermod -aG docker $USER
#=======================

echo "Installing docker-compose"
sudo apt-get install python3 python3-pip
pip -v install docker-compose
docker-compose --help
if command -v docker-compose >& /dev/null; then echo "Docker-Compose installed.."; else echo "Error installing Docker-Compose"; fi
echo "alias dc='docker-compose'" >> .bashrc

echo "Cleaning.. Removing.."
sudo apt autoremove
sudo apt autoclean

