#!/usr/bin/env python3
import sys

__EXPL__ = """
How it works?:
    just the **naive** check for simplicity
    if a number modded by its smaller adjacents is 0 its not prime
    because it is evenly divisable by that adjacent.
"""


def is_prime(n):
    if n in (2, 3, 5, 7, 11, 13):
        return True

    if n in (0, 1) or (n % 2) == 0:
        return False

    for adj in range(9, n+1):
        if n % adj == 0:
            return False

    return True


def main(args=None):
    number = int(args[1], 10)
    print("Number: ", number)
    return is_prime(number)


if __name__ == "__main__":

    __VERSION__ = "0.1.2"

    if len(sys.argv) <= 1:
        print()
        print(f"Usage: {sys.argv[0]} <number>")
        print()
        print("-v,-V show latest version of this script")
        print()
        print("2,3,5,7,11,13 are prime no need to call this program")
        print("0,1,even numbers, and even sqrts like sqrt(9) are not prime")
        print()
        print(__EXPL__)
        sys.exit(1)

    if sys.argv[1] in ("-v", "-V"):
        print(f"is_prime version: v{__VERSION__}")
        sys.exit(0)

    if len(sys.argv) > 2:
        print("Just one number or a single argument please!!")
        sys.exit(1)

    print(main(args=sys.argv))
