#!/usr/bin/env python

import os
import sys

if len(sys.argv) < 2:
    print("ERROR: need ft and target dir (.go, or .c etc. and ./src etc.)")
    sys.exit(1)

ft=sys.argv[1]
dire=sys.argv[2]
lines = []
for root, dirs, files in os.walk(dire):
	for file in files:
		if file.endswith(ft):
			fp = os.path.join(root, file)
			with open(fp) as f: count = sum(1 for line in f)
			lines.append((count, fp))

cleaned = sorted(lines, key=lambda x: x[0], reverse=True)
[print("LOC", x[0], "SOURCE", x[1]) for x in cleaned[:20]]

