#!/usr/bin/env python

import sys


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("Usage: parts <target>")
        return 1
    target: int = int(argv[1])
    print(f"Equal Divisors of: {target}")
    print("---------------------")
    for i in range(1, target + 1):
        if target % i == 0:
            print(i)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))

