#!/usr/bin/env python3

from argparse import ArgumentParser, Namespace
import os
import sys
from subprocess import Popen, PIPE, STDOUT
import time
from tqdm import tqdm #type: ignore

def main(args=None) -> None:
    total=0
    prog_bar = tqdm(total=total)
    child = Popen(args.program, shell=True,
                 stdin=PIPE, stdout=PIPE,
                 stderr=STDOUT, close_fds=True)

    while child.poll() is None:
        prog_bar.set_description(f"Processing child {child.pid}")
        prog_bar.refresh()
        sys.stdout.flush()
        time.sleep(.015)
        prog_bar.update(n=1)
    child.wait()
    child.kill()

if __name__ == "__main__":
    parser: ArgumentParser = ArgumentParser()
    parser.add_argument("--program", type=str, help="provide a program as input. eg sleep 1")
    args: Namespace = parser.parse_args()
    main(args=args)

