#!/bin/bash

set -o vi

# https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html
shopt -s cdspell dirspell
shopt -s checkhash
shopt -s failglob
shopt -u hostcomplete
shopt -s cmdhist
shopt -s histappend

alias ..="cd ../"
alias ls="ls --color=auto --author -bcFA -N -t"
alias ll="ls -hls"
alias grep="grep --color=auto"
alias clear="printf '\e[1;1H\e[2J'"

bin2dec() { echo "obase=10;ibase=2;$1" | bc; }
bin2hex() { echo "obase=10000;ibase=2;$1" | bc; }
dec2bin() { echo "obase=2;$1" | bc; }

__add_to_path_if_not_exists() {
    [[ -d "$1" ]] && [[ ! ":$PATH:" =~ ":$1:" ]] && export PATH="$1:$PATH"
}

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_BIN="$HOME/.local/bin"
__add_to_path_if_not_exists "$XDG_DATA_BIN"

__add_to_path_if_not_exists "$HOME/.local/scripts"
__add_to_path_if_not_exists "$HOME/.local/scripts/debian" # debian installers
__add_to_path_if_not_exists "$HOME/.local/scripts/dist" # generic installers

[[ -d "$HOME/.local/scripts/env-completion" ]]; source "$HOME/.local/scripts/env-completion";
[[ -f "$HOME/.local/scripts/disable-capslock" ]]; source "$HOME/.local/scripts/disable-capslock"

worktrees() {
    __doc__="Fuzzy Find Selection that moves you into the selected worktree automatically."
    [[ ! -d ".worktrees" ]] && echo ".worktrees directory doesnt exist" && return 1;
    dest=$(find ".worktrees" -maxdepth 1 -type d -not -path ".worktrees" \
    | fzf --cycle --no-multi-line --list-border block --header "Move to worktree");
    [[ -d $d ]]; cd "$dest"; tmux new -s "$dest"
}
