#!/bin/sh

# remove local branches without remote counterparts
git fetch -p
for br in $(git branch -vv | grep ': gone]' | awk '{print $1}'); do git br -D "$br"; done

# fetch all and prune
git fetch --all --prune
