#!/bin/bash

set -eu

rm -rf "$(brew --cache)"
brew upgrade --fetch-HEAD --greedy

echo "-------------DOCTOR------------"
brew doctor
echo "-------------------------"

echo "Cleaning..."

brew autoremove && brew cleanup

echo "All done!"
