#!/bin/bash


declare -a terminal_ansi_colors=(
	'1f1f1f' 'cc9393'
	'5f7f5f' 'ffd7a7'
	'8cb0d3' '8f8f8f'
	'71d3b4' 'dfe4cf'
	'6f6f6f' 'ecb3b3'
	'ffd7a7' '8cb0d3'
	'8f8f8f' '71d3b4'
	'dfe4cf' 'ffcfaf'
)

for color in "${terminal_ansi_colors[@]}"; do
	/Applications/Firefox.app/Contents/MacOS/firefox-bin \
		--new-tab "https://www.color-hex.com/color/$color"
done
