#!/bin/bash

sudo apt install git python3 packaging-dev equivs

git clone --recurse-submodules https://github.com/ungoogled-software/ungoogled-chromium-debian.git

git -C ungoogled-chromium-debian checkout --recurse-submodules TAG_OR_BRANCH_HERE

mkdir -p build/src
cp -r ungoogled-chromium-debian/debian build/src/
cd build/src

echo 'UPLOADER_HERE' > debian/uploader.txt

./debian/scripts/setup debian

sudo mk-build-deps -i debian/control
rm ungoogled-chromium-build-deps_*

./debian/scripts/setup local-src

dpkg-buildpackage -b -uc

