---
version: "3.7"

volumes:
  mysqldb_data:

services:
  mysqldb:
    image: mysql:latest
    container_name: mysql_managed_local
    restart: always
    volumes:
      - mysqldb_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_HOST=localhost
