BIN_DIR=$(HOME)/.local/bin
DATA_DIR=$(HOME)/.local/share/mdb/docker

all: checks linking

.PHONY: all

checks:
	[[ ! -d $(BIN_DIR) ]]; mkdir -p $(BIN_DIR); [[ ! -d $(DATA_DIR) ]]; mkdir -p $(DATA_DIR);

linking:
	ln -sf $(PWD)/mdb $(HOME)/.local/bin/mdb
	cp -a $(PWD)/docker/* $(HOME)/.local/share/mdb/docker
